name: smartkitchen
description: Smart application for cooking passionats

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^1.0.0
  font_awesome_flutter: ^8.7.0
  calendar_strip: ^1.0.4
  sqflite: ^1.1.7+2
  flutter_sqflite_manager: ^0.1.1
  string_similarity: ^1.0.1
  marquee: ^1.3.1
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  rxdart: ^0.24.1
  meta: ^1.1.8
  shared_preferences: ^0.5.7+3

  intro_slider: ^2.2.5
  flutter_speed_dial: ^1.2.1
  numberpicker: ^1.1.0
  provider: ^4.0.4
  percent_indicator: ^2.1.1
  cloud_firestore: ^0.12.9
  firebase_core: ^0.4.0+1
  firebase_analytics: ^4.0.2
  firebase_auth: ^0.11.1+3
  shake: ^0.1.0
  flutter_duration_picker: ^1.0.0
  path_provider: ^1.2.0

  flushbar: ^1.10.4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  assets:
    - assets/food12.jpg
    - assets/back1.jpg
    - assets/back2.jpg
    - assets/ciasto.jpg
    - assets/cotta.jpg
    - assets/jajecznica.jpg
    - assets/kanapka.jpg
    - assets/kawa.jpg
    - assets/lody.jpg
    - assets/makaron.jpg
    - assets/platki.jpg
    - assets/salatka.jpg
    - assets/schabowy.jpg
    - assets/sushi.jpg
    - assets/zapiekanka.jpg
    - assets/ziemniaki.jpg
    - assets/ingredient.jpg
    - assets/slider1.jpg
    - assets/slider2.jpg
    - assets/slider3.png
    - assets/slider4.jpg
